parameters:
    locale: 'es'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventSubscriber\LocaleSubscriber:
        arguments:
            $defaultLocale: '%locale%'
        tags: ['kernel.event_subscriber']

    App\EventSubscriber\TraductorRespuestaSubscriber:
        tags: ['kernel.event_subscriber']

    App\Service\TraductorDinamico: ~

    App\Service\TraductorExtension:
        tags: ['twig.extension']